### ISSUE TITLE
Ongoing Questions

### ISSUE THREAD

**Issue by brianamarie** [githubschool/apr-16#2]
There are many ways and places to ask questions. 
- Please feel free to interrupt me during class with questions on your microphone or in chat. 
- Post questions in this issue.
- Email me if you'd like to keep questions private (brianamarie@github.com)

**Comment by nekia** [comment]
FYI

[Solved: Blue line next to various issues in milestone - GitHub Community Forum](https://github.community/t5/How-to-use-Git-and-GitHub/Blue-line-next-to-various-issues-in-milestone/td-p/6007)
> A colleague solved the mystery for me: the blue lines indicate that you have an unread notification associated with that issue. So, other people don't necessarily see the blue lines just because you do.

https://github.com/StylishThemes/GitHub-Dark/issues/371

**Comment by brianamarie** [comment]
@nekia Thank you for finding the answer! Very interesting. 😄

**Comment by kut-arika** [comment]
What repository should I use for teachback?

**Comment by brianamarie** [comment]
@kut-arika I've posted a long response in https://github.com/githubschool/apr-16/issues/3#issuecomment-381961091, the issue for teachbacks. I think it will make it more easily discoverable for others in the future. 😄 Thank you for the very good question!

**Comment by githubteacher** [comment]
Can pre-commit hooks be shared between teammates?

**Comment by stoe** [comment]
To share pre-commit hooks, or any other client side Git hook, maybe a https://github.com/github/scripts-to-rule-them-all pattern that copies the hook file into .git/hooks can be used. 
Additional benefit, the hook script itself becomes part of the repository.
