### ISSUE TITLE
Teachbacks

### ISSUE THREAD

**Issue by brianamarie** [githubschool/apr-16#3]
# Teachbacks 

### What are Teachbacks? 
This training has two parts: One part is the class that I teach, and the other part is when **you** teach. This way, you will not only learn the content, but you will practice teaching the content. 

**The Teachback videos are required to complete the training and receive endorsement.**

To do this, please use the links below. Each link is a Zoom video room. When you join, it will **automatically start recording**. When you leave the call, the recording will process, and a link will be sent to me. The Zoom video rooms will be available 24/7 for 31 days. 

You can do this by yourself, but it would be best to coordinate this with others. If you are joining while someone else teaches, you will learn by having a review of the content, and seeing how they teach. You also will be able to provide feedback about what they did well and what they can continue to focus on in the future for improvement. This is the reason that there are multiple people per URL.

I will email feedback to each of you with the email address I have on file for you once each video is processed. 

### Teachback room 1: https://github.zoom.us/j/440569808
- @prayuja-patil
- @arugupta
- @YuichiNukiyama
- @reiko7
- @yope3

### Teachback room 2: https://github.zoom.us/j/787432141
- @hitochan777
- @ono-hirosato
- @nekia
- @sskhk
- @m1a2i3

### Teachback room 3: https://github.zoom.us/j/595761935
- @f14d
- @shimazaki-yoshiyuki
- @sakaiyu
- @hirofu
- @suwa-yuki

### Teachback room 4: https://github.zoom.us/j/371234962
- @kut-arika
- @gh7166
- @hideakikondo
- @YorozuNaoki

### Teachback room 5: https://github.zoom.us/j/350667425
- @RanjithPanda
- @gzfgk7
- @Shashankswat
- @RadaKichenin
- @prasadnagarale123

### Teachback room 6: https://github.zoom.us/j/767339423
- @priyankaghongade
- @mayankparashar
- @ashokbhardwaj
- @rajansinghal
- @abhaybhale

**Comment by githubteacher** [comment]
- Introduction - Editing on GitHub: 1.5 hours - 2.5 hours
- Merging Pull Requests - Resolving Merge Conflicts, and explaining the [Day 2 Merge Conflict Activity](https://githubtraining.github.io/training-manual/GH4D/app_day2_mergeconflict.html): 1.5 - 2.5 hours
- Workflow review - Reverting commits 1.5 - 2.5 hours 
- Helpful Git Commands - Merge strategies: 1.5- 2.5 hours

**Comment by brianamarie** [comment]
## Preparing repositories for Teachbacks 

#### Project 1: Slides
- Add a slide
- Practice first merge conflict
Please use this same class repository, apr-16, for the first project's activities. 

#### Project 2: Merge conflicts
To prepare your local repository to be ready for teaching, use the following commands. 

```
git checkout master
git reset --hard 1095c8c
git push --force
git checkout cb8731a
git checkout -b manual2
git push -u origin manual2
(open pull request)
git checkout 6b50ac7
git checkout -b css-changes2
git push -u origin css-changes2
(open pull request)
git checkout 945ca60
git checkout -b readme-update2
git push -u origin readme-update2
(open pull request)
```

#### Project 3: GitHub Games 
- Edit the description to no longer be the correct URL
- In your own copy of GitHub Games:
```
git checkout master
git reset --hard 73c762c
git push --force
```

#### Project 4: Working locally
Create a new repository for these activities.
